@startuml covid sos datamodel
class User {
  *email: string
  *name: string
  *lastName: string
  *gender: GenderType
  *address: string
  *phone: string
  roles: RoleType[1..*]
}

User <|-- Carrier
User <|-- Manager
User <|-- Beneficiary

class CollectionCenter {
  *name: string
  *address : string
}

class Merchandise {
  *arrivalTime*: DateTime
  *collectionCenter: CollectionCenter
  *photo: Image
  description: string
  departureTime: DateTime
}

class Request {
  *beneficiary: Beneficiary
  *status: RequestStatusType
  *description: string
  carrier: Carrier
  aidPackage: Merchandise[1..*]
  isApproved(): bool
}

enum RoleType {
  Beneficiary
  Manager
  Carrier
}

enum RequestStatusType {
  New
  Approved
  Rejected
  Delivered
}

enum GenderType {
  Male
  Female
  Other
}

Manager "0..*" -- "1..* centers" CollectionCenter : manage >
CollectionCenter "  1 collectionCenter" -- "0..* products" Merchandise : has >
Carrier "0..1 carrier" -- Request : delivers >
Beneficiary "1 beneficiary" -- Request : requests >
Request x-> "1..*" Merchandise
@enduml
