@startuml covid sos datamodel
class Person {
  *email: string
  *name: string
  *address: string
  *phone: string
  province: string
  canton: string
  distrito: string
}

class Beneficiary {
}
Person <|-- Beneficiary

class User {
  roles: RoleType
}

Person <|-- User

User <|-- Carrier
User <|-- Manager

class CollectionCenter {
  *name: string
  *address : string
  *email: string
  province: string
  canton: string
  distrito: string
  exactAddress: string
}

class Manager {
  *documentId: string
}

class Merchandise {
  *arrivalTime: DateTime
  *collectionCenter: CollectionCenter
  *photo: Image
  description: string
  departureTime: DateTime
}

class Request {
  *beneficiary: Beneficiary
  *status: RequestStatusType
  *description: string
  *photo: Image
  carrier: Carrier
}

enum RoleType {
  Director = 4
  Manager = 3
  Carrier = 2
  Visitor = 1
}

enum RequestStatusType {
  New
  Approved
  Rejected
  InTransit
  Delivered
}

Manager "0..1" -- "1..* centers" CollectionCenter : manage >
CollectionCenter "  1 collectionCenter" -- "0..* products" Merchandise : has >
Carrier "0..1 carrier" -- Request : delivers >
Carrier "0..*" -- "0..1" CollectionCenter : affiliated to >
Beneficiary "1 beneficiary" -- Request : requests >
@enduml
