@startuml covid sos datamodel
class Person {
  *email: string
  *name: string
  *address: string
  *phone: string
  documentId: string
  province: string
  canton: string
  distrito: string
}

class Beneficiary {
  *documentId: string
  type: BeneficiaryType
}

class User {
  role: RoleType
}
Person <|-- User

User <|-- Beneficiary
User <|-- Carrier
User <|-- Manager

class CollectionCenter {
  *name: string
  address : string
  *email: string
  province: string
  canton: string
  distrito: string
  exactAddress: string
}

class Manager {
  *documentId: string
}

class Carrier {
  *address : string
}

class Merchandise {
  *arrivalTime: DateTime
  *collectionCenter: CollectionCenter
  *photo: Image
  description: string
  departureTime: DateTime
}

class AidPackage {
  *beneficiary: Beneficiary
  *status: AidPackageStatusType
  *description: string
  *photo: Image
  *collectionCenter: CollectionCenter
  carrier: Carrier
}

enum RoleType {
  Director = 4
  Manager = 3
  Carrier = 2
  Visitor = 1
  Beneficiary = 0
}

enum AidPackageStatusType {
  New
  Approved
  Rejected
  InTransit
  Delivered
}

enum BeneficiaryType {
  Critical = 3
  Accepted = 2
  Rejected = 1
}

AidPackage "0..*" -- "1" CollectionCenter
Manager "0..1" -- "1..* centers" CollectionCenter : manage >
CollectionCenter "  1 collectionCenter" -- "0..* products" Merchandise : has >
Carrier "0..1 carrier" -- AidPackage : delivers >
Carrier "0..*" -- "0..1" CollectionCenter : affiliated to >
Beneficiary "1 beneficiary" -- AidPackage : AidPackages >
@enduml
